#+TITLE: Magnetic Dance
#+SUBTITLE: An Art-Science Experiment in Embodied Interaction

* Introduction

** Overview
 The title of this presentation could be "Dancing and Weaving Songs with Electrons and Quanta:  Emergence of metric patterns in telematic dance performance."

 The project spans a wide spectrum of scientific and artistic fields, from Artificial Life and Quantum Biology to Telematic Dance, Live Coding and Embodied Interaction in Music Performance.

 The project was concieved at the beginning of 2018 and is still in its initial phase.  Here I will report on the conceptual background of the project and the technical work so far.

 Finally, I will mention some plans for the immediate future, and open up the stage for discussion.

** Background

   The project arose under the circumstances of my sabbatical research stay in Tokyo in Spring and Summer of 2018.  Due to the need to participate at an Art-Science exhibition organised by my colleague Prof. Spyros Verykios during that period, I had to devise a way to perform remotely that would be original and make sense in the context of the exhibition.  As it developed, the project incorporated other research topics and ideas that had preoccupied me ever since my participation in the previous installment of the EASTN Project (2014-2015).  The 

*** Initial stimulus: From sonification of magnetic fields to biosemiotics

 The initial prompt for project came from an Art-Science exhibition organized by my colleague at the Audiovisual Arts Department of Ionian University, Prof. Spyros Verykios.  Inspired by the 1966 Science Fiction film "Fantastic Voyage", Spyros formulated a call for works dealing with navigating the inner space of humans both figuratively and literally, and by extension also the discovery of parallels between Inner and Outer Space (in the thelematic sense, "As Above So Bewow").  The exhibition is showing at the National Observatory of Athens (NOA) till end of this month (https://cosmonauts1.wixsite.com/cosmonauts/athens).  I had been invetigating the possibility of a collaboration with NOA dealing with the sonification of magnetic storms since 2017, and thus I thought it would be a good opportunity to participate.  However, since I had planned to be on sabbatical in Tokyo from May 2018, the only way to participate with a live event would be remotely. The initial idea was to scan the local magnetic field of the two locations involved, Athens and Tokyo using easily available magnetic sensors such as those used in mobile devices for navigation, and to use the data for sonification.  The performers would wear magnetometers on their body and explore variations in the ambiend magnetic field in this way, usind sound as feedback for their orientation.  Already this basic idea seem interesting as it introduced magnetism as a sense source for humans, which suggested parallels to alternative sense forms in other life forms, such as microorganisms or plants.  Just as these organism use phototropism or chemotropism to adapt to search for energy sources in their environment, the dancers would use the ambient magnetic field to navigate or adapt their sonic environment as a metaphoric source of energy.  Moreover the use of such an exotic stimulus source as sense suggested associations with early work in the field of biosemiotics which had interested me for a while.  Jakob von Uexk체ll's 1934 paper "A Stroll through the Worlds of Animals and Men: A Picture Book of Inisible Worlds" proposed a very early model of perception of the environment built in bottom up manner - without the preconceptions about perception inherent in human-centric views. In this paper, he introduced the notion of environment (Umwelt) in Biology and Comparative Psychology, and thus opened the way to Environmental Sciences. 

*** Enter Artificial Life and Autopoiesis

*** Enter Live Coding, Weaving and Traditional African Music

*** An aftherthought: Rhythmanalysis

* Implementation

** Sensors

** Wearable Wireless Technology

** Software for Embedded Devices and Internet of Things (IoT)

** Peerformance Model on SuperCollider

** Network aspects

** Partners

* Outlook

* References



Uexk체ll, Jakob von. 1934.  "A Stroll through the Worlds of Animals and Men: A Picture Book of Invisible Worlds" (original Title: "Streifz체ge durch die Umwelten von Tieren und Menschen: Ein Bilderbuch unsichtbarer Welten"). In: Verst채ndliche Wissenschaft, Vol. 21. Berlin, J. Springer.

Virgo, Nathaniel. 2011. Thermodynamics and the Structure of Living Systems. PhD Thesis, University of Sussex.

Virgo, Nathaniel, .... 2011. 


** Web
 http://sro.sussex.ac.uk/6334/1/Virgo%2C_Nathaniel.pdf


 http://www.massey.ac.nz/~wwpapajl/evolution/lecture1/docs/tick.htm

